services:
  - type: web
    name: interactive-qa-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd server && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false  # This will be set manually in Render dashboard
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: false
      - key: ENVIRONMENT
        value: production
    autoDeploy: true
    healthCheckPath: /health
